{
 "title": "Flask App",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"devops:5000\"}",
     "legendFormat": "Memory Usage of App"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"prometheus:9090\"}",
     "legendFormat": "Memory Usage of Prometheus"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"devops:5000\"}[$__rate_interval])",
     "legendFormat": "CPU Usage by App"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"prometheus:9090\"}[$__rate_interval])",
     "legendFormat": "CPU Usage by Prometheus"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(flask_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}