name: CD - Build and Deploy

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{
            secrets.DOCKER_HUB_USERNAME
          }}
          password: ${{
            secrets.DOCKER_HUB_ACCESS_TOKEN
          }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/devops:latest,
                ${{secrets.DOCKER_HUB_USERNAME}}/devops:${{github.sha}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{
        steps.deploy-to-webapp.outputs.webapp-url
      }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'saj'
          slot-name: 'production'
          publish-profile: ${{
            secrets.AZURE_WEBAPP_PUBLISH_PROFILE
          }}
          images: ${{secrets.DOCKER_HUB_USERNAME}}/devops:${{github.sha}}
